### PR TITLE
Removed unnecessary imports

### PR DESCRIPTION
**Pull request by Israel77**
Removed the unused imports of the libraries "os" and "Image" (the latter was causing the application to not be able to run with only the dependencies documented on README) from the file 'pyxhook.py'.

### CODE REVIEW

**Comment by okiyama** [comment]
@Israel77 thanks so much for the contribution! I don't have a Linux box handy to test this out. Did you run the code with your changes and make sure everything works okay?

**Comment by Israel77** [comment]
> @Israel77 thanks so much for the contribution! I don't have a Linux box handy to test this out. Did you run the code with your changes and make sure everything works okay?

Yes, I tested it with **(C)Python 2.7.17** running on **Linux Mint 19.3**. The auto clicking and the clicking method selection works just fine, though I didn't bother to find a good way to test wether or not the function "MS of random delay" is working as expected, but I don't see why it would not.

When I tried to run the program for the first time I got an error due to not having the "Image" module installed. I tried to find which library implements it but was unsuccessful, then I looked up on my IDE where this module was used to try to replace it with some alternative, but I found no reference to this module anywhere in the codebase, so I removed the import and the program worked as expected.

I began looking for other unused imports and found out that "os" was imported but not used in the same file.

**Comment by okiyama** [comment]
Awesome, thanks so much for the thorough reply! I'll merge this in, if anyone complains it's busted I'm blaming you :P

**Comment by Israel77** [comment]
> Awesome, thanks so much for the thorough reply! I'll merge this in, if anyone complains it's busted I'm blaming you :P

Fair enough 😅.

I will probably make some more pull requests or fork it soon to try to add the missing functionalities of selecting the key to trigger clicking and select the mouse button (I needed auto right-clicking for my application, so I had to hard code it in my local version), maybe even try to update to Python 3 if I feel like it 😁

**Comment by okiyama** [comment]
That'd all be awesome! Be my guest and I'll be happy to review PRs for you :D

**Pull request merged**
